#!/bin/bash

#Initialise the EXTENSION of the files to be spa (can be changed in case the old format is used)
EXTENSION="spa"
SPC=""
# Parse the arguments
# I'm changing this since the old argument grabber wasn't working
# and this is easier than debugging it.
while getopts 'f:sch' flag; do
	case $flag in
		f)
		    FILEPATH=$OPTARG
		    ;;
		s)
		    EXTENSION="spc"
		    SPC="-s"
		    ;;
		c)
		    CLASSIC="-c"
		    ;;
		h)
		    help=1
	esac
done

if [ -n "$help" ]; then
	echo "Usage: $0 -f path_to_ftir_files"
	echo "Optional: add -s if the file extension is spc instead of spa"
	echo "Optional: add -c to do the classic renaming instead of the newer default"
	echo "Optional: add -h to print this help statement instead of renaming anything"
	exit
fi

set -- "${POSITIONAL[@]}" # restore positional parameters

# Check to see if the filepath argument was provided
if [ -z "${FILEPATH}" ]
then
      echo Please provide the path to the FTIR files on your USB key e.g. "${HOME}"/LANG/FTIR
      exit
else
      # Ensure that the filepath is valid
      PARENTDIR="$(dirname "${FILEPATH}")"
	echo "${PARENTDIR}"
      if [ ! -d "${FILEPATH}" ] 
      then
          echo "Directory "${FILEPATH}" DOES NOT exist!" 
          exit
      # Check to see if the required .XLSX file is present
      else
          if [ -f "${FILEPATH}"/FTIR.XLSX ]; then
		EXCELFILE="${FILEPATH}"/FTIR.XLSX 
		
          elif [ -f "${PARENTDIR}"/FTIR.XLSX ]; then
		EXCELFILE="${PARENTDIR}"/FTIR.XLSX
	  else
              echo "Cannot locate FTIR.XLSX file in "${FILEPATH}" or "${PARENTDIR}"!" 
              exit
          fi
          # Check to see if .spa/.spc files are present in the supplied path
          SPCFILES=`ls "${FILEPATH}"/*."${EXTENSION}" 2> /dev/null`
          if [ -z "${SPCFILES}" ]
          then
              echo "Cannot locate ."${EXTENSION}" files in "${FILEPATH}"!" 
              exit
          else
              echo "Using FTIR file path: "${FILEPATH}""
	      echo "Using Excel file: "${EXCELFILE}"" 
          fi
      fi
fi

# Copy Files USB to /mnt/nas2/raw_sequence_data/ftir
echo "Copying files from USB to /mnt/nas2/raw_sequence_data/ftir/working_dir"
# Make the working directory on the NAS (if necessary)
mkdir -p /mnt/nas2/raw_sequence_data/ftir/working_dir/
cp -r "${FILEPATH}"/*."${EXTENSION}" /mnt/nas2/raw_sequence_data/ftir/working_dir/
cp -r "${EXCELFILE}" /mnt/nas2/raw_sequence_data/ftir/working_dir/
sleep 10

# Run Renamer
echo "Running renamer.py"
renamer.py -p /mnt/nas2/raw_sequence_data/ftir/working_dir -f /mnt/nas2/raw_sequence_data/ftir/working_dir/FTIR.XLSX -o /mnt/nas2/raw_sequence_data/ftir/working_dir/renamedfiles "${CLASSIC}" "${SPC}"
sleep 5

# Compress Files
echo "Compressing files"
zip -j /mnt/nas2/raw_sequence_data/ftir/working_dir/renamedfiles/FTIR.zip /mnt/nas2/raw_sequence_data/ftir/working_dir/renamedfiles/*."${EXTENSION}"
sleep 5

# Move Zip to USB
echo "Moving archive to USB"
mv /mnt/nas2/raw_sequence_data/ftir/working_dir/renamedfiles/FTIR.zip "$(dirname "${FILEPATH}")"
sleep 2

# Move raw files from working_dir to raw_files
echo "Moving raw files to storage"
mv /mnt/nas2/raw_sequence_data/ftir/working_dir/*."${EXTENSION}" /mnt/nas2/raw_sequence_data/ftir/raw_files/

# Move renamed files from working_dir/renamed to renamedfiles
echo "Moving renamed files to storage"
mv /mnt/nas2/raw_sequence_data/ftir/working_dir/renamedfiles/* /mnt/nas2/raw_sequence_data/ftir/renamedfiles/

#Delete Old FTIR
echo "Removing FTIR.XLSX from NAS"
rm /mnt/nas2/raw_sequence_data/ftir/working_dir/FTIR.XLSX

# Delete original files from USB
echo "Removing original files from USB"
rm "${FILEPATH}"/*."${EXTENSION}"

echo "Complete!"
